name: iOS starter workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_with_signing:
    runs-on: macos-latest
    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: checkout repository
        uses: actions/checkout@v3

      - name: Install the Apple certificate and provisioning profile
        env:
          WORKSPACE: 'Fluxstore.xcworkspace'
          ARTIFACT_NAME: ${{ 'Fluxstore.ipa' }}
          ARTIFACT_PATH: ${{ 'development/' }}
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          P12_KEY_BASE64: ${{ secrets.P12_KEY_BASE64 }}
          ARCHIVE_PATH: './build/Fluxstore.xcarchive'
          EXPORT_PATH: 'development/'  # Specify the export path here
          PLIST_PATH: 'Fluxstore/Info.plist'
          SCHEME_NAME: 'Fluxstore'
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Build and export iOS
        uses: yukiarrr/ios-build-action@v1.11.0
        with:
          project-path: Fluxstore.xcodeproj
          p12-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          mobileprovision-base64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          code-signing-identity: 'Apple Development'
          team-id: 2Y7ZL4NR85
          workspace-path: Fluxstore.xcworkspace
          configuration: "Debug"
          export-method: "development"

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     # name: ${{ env.ARTIFACT_NAME }}
      #     path: |
      #       $RUNNER_TEMP/work/DemoBuild/DemoBuild/output.ipa

      - name: Upload application
        uses: actions/upload-artifact@v3
        with:
          name: app
          # path: Users/runner/work/DemoBuild/DemoBuild/output.ipa
          # you can also archive the entire directory 
          path: /Users/runner/work/DemoBuild/DemoBuild/output.ipa
          retention-days: 3
